import { Sniglet, Geist_Mono, Inter, Righteous } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const righteous = Righteous({
  variable: "--font-righteous-sans",
  subsets: ["latin"],
  weight: "400"
})

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
  weight: "400"
})

const sniglet = Sniglet({
  variable: "--font-sniglet-sans",
  subsets: ["latin"],
  weight: "400"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
